server:
  port: 8888

frontend:
  url: http://localhost:4200

spring:
  application:
    name: Social-Media

  jackson:
    time-zone: Asia/Ho_Chi_Minh
    date-format: yyyy-MM-dd HH:mm:ss

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:social_media}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
    username: ${DB_USER:root}
    password: ${DB_PASS:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver

  #  Redis Upstash
  data:
    redis:
      host: fresh-marmoset-4982.upstash.io
      port: 6379
      username: default
      password: ${REDIS_PASS}
      ssl:
        enabled: true
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: Asia/Ho_Chi_Minh

  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB

  devtools:
    add-properties: true


management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
        # include: health,prometheus,metrics

jwt:
  access-token-secret: "8mhZcWZVPhDeucdGaUQhUQoSkda3yjAtkBPJNP/4dvQy"
  refresh-token-secret: "Gu4jjMNk9oBnertRHqfRZJdHnz5jihbbnjAHeWNQbpg9"
  access-token-expiration: 360000000
  refresh-token-expiration: 360000000

aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  s3:
    bucket: social-networkings
    region: ap-southeast-1
  cloudfront:
    url: https://d28ic9z7shvx92.cloudfront.net

cloudinary:
  cloud_name: ${CLOUD_NAME}
  api_key: ${API_KEY}
  secret_key: ${SECRET_KEY}
